;; (altest "altest/test")

(assert 't)
(assert 'nil)
(deftest "Assert")
(assert '(= 1 1))
(assert '(/= 1 1))
(assert '(/ 1 0))
(deftest "Assert-eq")
(assert-eq '1 '(+ 1 0))
(assert-eq '1 '(+ 1 1))
(assert-eq '1 '(/ 1 0))
(deftest "Assert-error")
(assert-error '(/ 1 0))
(assert-error '(/ 1 1))
(deftest "All-pass")
(assert '(= 1 1))
(assert-eq '1 '(+ 1 0))
(assert-error '(/ 1 0))
